service: cornerservice # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    ATLASURI: ${file(./env.yml):ATLASURI}

plugins:
  - serverless-offline

functions:
  hello:
    handler: handler.hello
    events:
     - http:
         path: test
         method: get
  hellopost:
    handler: handler.hellopost
    events:
     - http:
         path: test
