
service: cornerservice # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: handler.hello
    events:
     - http:
         path: test
         method: get
         authorizer:
          arn: arn:aws:cognito-idp:us-east-2:349847673753:userpool/us-east-2_7rZyQ4s7p
